# Generated by Django 6.0.2 on 2026-05-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
    ]
