# Generated by Django 6.0.2 on 2026-03-09 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=998)),
                ('body_html', models.TextField(default='')),
                ('body_text', models.TextField(default='')),
                ('from_name', models.CharField(default='', max_length=255)),
                ('reply_to', models.CharField(default='', max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField()),
                ('sent_count', models.IntegerField()),
                ('spam_score', models.FloatField(blank=True, null=True)),
                ('spam_risk', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
