# Generated by Django 6.0.2 on 2026-03-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('senders', '0002_rename_name_sender_display_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='bounce_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='senders.sender'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='spam_risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
