# Generated by ChatGPT on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_campaign_bounce_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recipient_emails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
