# Generated by Django 6.0.2 on 2026-03-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_emailengagement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailengagement',
            new_name='campaigns_e_trackin_c92ded_idx',
            old_name='campaigns_em_trackin_aa4a4e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailengagement',
            new_name='campaigns_e_campaig_73c08f_idx',
            old_name='campaigns_em_campai_90cf67_idx',
        ),
        migrations.RenameIndex(
            model_name='emailengagement',
            new_name='campaigns_e_sent_at_d6ea5c_idx',
            old_name='campaigns_em_sent_at_4dcf77_idx',
        ),
    ]
