# Generated by Django 6.0.2 on 2026-03-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_rename_campaigns_em_trackin_aa4a4e_idx_campaigns_e_trackin_c92ded_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_url', models.URLField(max_length=2048)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='campaigns.campaign')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='campaigns.emailengagement')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailclickevent',
            index=models.Index(fields=['campaign', 'clicked_at'], name='campaigns_e_campai_6f09cf_idx'),
        ),
        migrations.AddIndex(
            model_name='emailclickevent',
            index=models.Index(fields=['campaign', 'clicked_url'], name='campaigns_e_campai_a3bf71_idx'),
        ),
    ]
