# Generated by Django 6.0.2 on 2026-03-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_emailclickevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailclickevent',
            new_name='campaigns_e_campaig_1feca4_idx',
            old_name='campaigns_e_campai_6f09cf_idx',
        ),
        migrations.RenameIndex(
            model_name='emailclickevent',
            new_name='campaigns_e_campaig_e21924_idx',
            old_name='campaigns_e_campai_a3bf71_idx',
        ),
    ]
