# Generated by Django 6.0.2 on 2026-04-14 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0007_rename_campaigns_e_campai_6f09cf_idx_campaigns_e_campaig_1feca4_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Welcome Email', 'Monthly Newsletter')",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email subject line", max_length=998
                    ),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, help_text="HTML version of the email"),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, help_text="Plain text version"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times this template was used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-use_count", "-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["recipient_email"], name="campaigns_e_recipie_25ca00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["opened_at"], name="campaigns_e_opened__7074b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["clicked_at"], name="campaigns_e_clicked_f9ee45_idx"
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("user", "name")},
        ),
    ]
