# Generated by Django 6.0.2 on 2026-05-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_emailtemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="ab_test_duration_hours",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="campaign",
            name="ab_test_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_ab_test",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CampaignVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1)),
                ("subject", models.CharField(max_length=998)),
                ("body_html", models.TextField(blank=True, default="")),
                ("body_text", models.TextField(blank=True, default="")),
                ("percentage", models.PositiveIntegerField(default=10)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("spam_score", models.FloatField(blank=True, null=True)),
                (
                    "spam_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "label")},
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="winner_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_campaigns",
                to="campaigns.campaignvariant",
            ),
        ),
        migrations.AddField(
            model_name="emailengagement",
            name="campaign_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="engagements",
                to="campaigns.campaignvariant",
            ),
        ),
    ]
