# Generated by Django 6.0.2 on 2026-03-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='sender',
            old_name='email',
            new_name='from_email',
        ),
        migrations.AddField(
            model_name='sender',
            name='_password',
            field=models.TextField(db_column='password', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='daily_limit',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='sender',
            name='emails_sent_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sender',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sender',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sender',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail / Google Workspace'), ('outlook', 'Outlook / Office 365'), ('custom', 'Custom SMTP')], default='gmail', max_length=20),
        ),
        migrations.AddField(
            model_name='sender',
            name='smtp_host',
            field=models.CharField(default=587, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sender',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sender',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sender',
            unique_together={('user', 'from_email')},
        ),
    ]
